### ISSUE TITLE
Off-by-one energy gauge error

### ISSUE THREAD

**Issue by roncli** [CDarrow/DXX-Retro#65]
DCL discussion: http://descentchampions.org/forum/viewtopic.php?f=5&t=462

DXX-Rebirth fix: https://github.com/dxx-rebirth/dxx-rebirth/commit/90e3c294643111692b7c6873fa68dc973e827ac8

Let me know if you'd rather me do the pull request for it, although it may be a few days.

**Comment by ryusei117** [comment]
Hmm, it seems this issue is more complex than I had thought. zico found a new bug that the fix for this one created, but for some reason, I can't reproduce the glitch he's seeing. I also found that the fix for this bug corrected only the OpenGL build and not the software renderer build. Might not want to copy the fix to Retro just yet; let's see how zico and Kp

**Comment by ryusei117** [comment]
Hmm, it seems this issue is more complex than I had thought. zico found a new bug that the fix for this one created, but for some reason, I can't reproduce the glitch he's seeing. ([Here's his report.](https://github.com/dxx-rebirth/dxx-rebirth/issues/169)) I also found that the fix for this bug corrected only the OpenGL build and not the software renderer build. ([Here's that one.](http://www.dxx-rebirth.com/frm/index.php/topic,2075.msg21996.html#msg21996)) Might not want to copy the fix to Retro just yet; let's see how zico and Kp handle these problems.

**Comment by roncli** [comment]
@zicodxx closed the bug as unable to reproduce in Rebirth, but it's definitely still an issue.

In fact, at 320x200, the area painted in black is... skewed.

![image](https://cloud.githubusercontent.com/assets/498929/12562865/3b81848a-c35c-11e5-832f-3fa65ed04c27.png)

**Comment by ryusei117** [comment]
Hold on, the bug that zico closed is different than the one in your screenshot. Check the screenshot in his report here:

* [d2x-offbyone.png](http://dxx-rebirth.com/tmp/d2x-offbyone.png)

There have been several different related bugs reported on various web sites; I'm not surprised it's causing confusion. :) Here's a list of all the ones I know about:

* Entropy found the original energy gauge bug. [I reported it on the Rebirth forum](http://www.dxx-rebirth.com/frm/index.php/topic,2075.0.html), and [Kp fixed it in the Rebirth development code](https://github.com/dxx-rebirth/dxx-rebirth/commit/90e3c294643111692b7c6873fa68dc973e827ac8).
* [I then found a few other bugs](http://www.dxx-rebirth.com/frm/index.php/topic,2075.msg21996.html#msg21996): Kp had fixed the energy gauge in the OpenGL build, but not the software renderer build, and the afterburner gauge had some problems in both builds.
* [zico found that Kp's fix had overcompensated](https://github.com/dxx-rebirth/dxx-rebirth/issues/169), creating a vertical yellow line on the energy gauge's left edge. I couldn't reproduce that bug, and zico later realized he couldn't reproduce it either - so he closed his own bug, suspecting that he had made a mistake in testing Kp's fix.

**Comment by roncli** [comment]
The bottom line is that the energy gauge is messed up pretty badly in a number of scenarios.  We'd need to get software rendering in retro working first (#62) and then we'd need to take inventory of exactly what the bugs in what renderers at what dimensions, so that we can figure out exactly what needs fixing.

All in all, this shouldn't really be a high priority bug, but it is one of those things that once seen can't be unseen. :)

**Comment by zicodxx** [comment]
After you guys talked about this, I tried to see if I could reproduce the issue reported here. The vertical 'off-by-one' is still a mystery for me and I closed this because I thought it was related to code not compiled perfectly clean (gauges.o still existing from an older revision or such). So I started messing with Multisampling on different resolutions and while I could *not*  reproduce the energy bar being skewed like this but on some resolutions I had the please to meet my old friend, the 'off-by-one' vertical bar again. Strangely, on another resolution I first tested this on (640x480 was my test and here it doesn't happen anymore). Even stranger - I first only saw this in D2X and not I only reproduce it in D1X. 

So yeah, there is still something very off in the drawing function that creates the lines over the energy bar and as @ryusei117 speculated, it definitely seems to be related to Multisampling. I'll go this down step by step and see what that is. Definitely an interesting bug and the unreliability in testing it, makes it a challenge. But soon as I found it, I'll post the reference here as well.

**Comment by roncli** [comment]
I had the bug happening on my Mac, so I created the jinx-65 on roncli/DXX-Retro, borrowing from both of @zicodxx's commits mentioned in this thread to get it operational.  I'm going to do some tests on my PC tonight to make sure I didn't break some of these 1990's resolutions people seem to want to use :) and then merge back if all goes well.

**Comment by roncli** [comment]
Sometimes I love programming.  And sometimes, THIS happens:

![image](https://cloud.githubusercontent.com/assets/498929/22324443/31168e1e-e35e-11e6-81f7-84f0d00fec6b.png)

Branch is jinx-65 on roncli/DXX-Retro, if someone can wants to try to explain why THIS is happening. :confused:

**Comment by roncli** [comment]
Same shot on mac:
![screen shot 2017-01-26 at 6 46 10 am](https://cloud.githubusercontent.com/assets/498929/22335356/4a77ab24-e393-11e6-9df1-8954b00bd26a.png)

**Comment by zicodxx** [comment]
Does this only happen with Multisampling/FSAA in place? That's the only way I am able to reproduce issues like that. The thing is that Rebirth can only scale pixel perfect if bitmaps are scaled accurately by 2, 3, 4, 5, etc. In the Mac data, the base of that is 640x480 which means you have a lot of resolutions that are simply not pixel accurate. That alone can be a reason for this. Then throw FSAA into the mix and with whatever interpolation it likes to use for the method in question and you can get all sorts of weird results. :)

**Comment by roncli** [comment]
I cannot get the bug to trigger on Mac, period.  I tried the Windows and Mac bacon files.

Problem with the Mac bacon files though... trying to use windowed mode causes a straight up crash.  Works fine with the Windows bacon files.  Happens on Retro 1.4x5 and Rebirth 0.58.1.  Haven't tried it with 0.59.100 yet.

**Comment by ryusei117** [comment]
@roncli: Interesting - using [the `jinx-65` branch on `roncli/DXX-Retro`](https://github.com/roncli/DXX-Retro/tree/jinx-65), I can't reproduce that new bug on GNU/Linux. I tried the resolutions 320 x 200, 320 x 240, and 640 x 480 and a number of higher ones, with and without multisample anti-aliasing, with the MS-DOS game data and the Mac OS game data ("bacon files" should seriously be their official name :-P ). For some strange reason, this might be a truly Windows-only bug.

I can use window mode with the Mac OS game data without crashing, but note that using any resolution less than 640 x 480 will cause a crash. That's because the Mac OS data's menu backgrounds, cockpit, and other such textures are 640 x 480 - and I guess the engine can't scale them down. Might that have been the problem you were having?

**Comment by roncli** [comment]
Finally got this fixed.  What I did was instead of drawing it row by row was to just do a rectangle.  That function also does it row by row, sure, but it uses uscanline instead of uline.  Worked in all cases.  I'm going to close this, but feel free to checkout roncli/DXX-Retro@7b13ec1 and see if there are any issues for you.
