### ISSUE TITLE
Random crash on zero energy

### ISSUE THREAD

**Issue by roncli** [CDarrow/DXX-Retro#69]
I cannot get this to happen consistently, but whenever your ship hits zero energy, there's a chance your game can hard crash.  I've had this happen in single player, in DCL matches, and in anarchy.  I've looked over the code and can't for the life of me find this bug.

**Comment by tueidj** [comment]
This is possibly due to some undefined behaviour in the original D1 code, specifically line 1175 in game.c; do_laser_firing_player() sets Global_laser_firing_count to 0 but the previous value might be cached by the earlier function.
Though I wouldn't expect this to cause a crash, rather all attempts to fire a laser while having zero energy would "pile up" and simultaneously be fired in one frame as soon as energy went above zero. But that's the thing about undefined behaviour...

**Comment by roncli** [comment]
It's not SETTING Global_laser_firing_count, it's DECREMENTING it.  In fact, if you dig into the code, all that `do_laser_firing_player()` will return is a 1 or a 0.  And, immediately after this, it sets the lower bound of `Global_laser_firing_count` to 0, so if it goes below 0 it is immediately reset to 0.

**Comment by vLKp** [comment]
Can you obtain a backtrace and register context at the time of the crash?  Knowing the faulting instruction might provide some clue about how it broke.

**Comment by roncli** [comment]
Interesting to note that I don't think this has ever happened in any version I've compiled (ie: I've not seen it in 1.4X5) or in Rebirth 0.58.1 (haven't tried in the beta yet).  I'm going to do some testing next time I'm in the code, and if I can't get it to reproduce I'll just close this.

**Comment by roncli** [comment]
Yeah, this just isn't happening in the newest versions, so closing!

**Comment by tueidj** [comment]
Roncli: do_laser_firing_player() SETS Global_laser_firing_count to 0:
https://github.com/CDarrow/DXX-Retro/blob/50ec7ba6e058cc0d90ca332d12059de2700aa69b/d1/main/laser.c#L1225
But the way the code in game.c is written, the previous value of Global_laser_firing_count has already been evaluated and will be used for the subtraction:
https://github.com/CDarrow/DXX-Retro/blob/50ec7ba6e058cc0d90ca332d12059de2700aa69b/d1/main/game.c#L1175
This can lead to Global_laser_firing_count gradually building up in certain cases (insufficient energy/ammo).

**Comment by vLKp** [comment]
Generally, global variables do not get cached unless the compiler can prove that it has no observable effect on the program.  You cited:

```c++
		if (Global_laser_firing_count)
			Global_laser_firing_count -= do_laser_firing_player();
```

This should evaluate as:

```
	cmpl $0,Global_laser_firing_count
	je 0f
	call do_laser_firing_player
	subl %eax,Global_laser_firing_count
0:
```

This does **not** cache the value for the purpose of the subtraction, so `Global_laser_firing_count` will be zeroed by `do_laser_firing_player`, then decreased by the return value.  The next two lines catch the frequently hit case where this causes the value to go negative.  The only way this value would build up is if `do_laser_firing_player` returned negative numbers, which it does not.

If you still think this is wrong, please explain the undefined behaviour in more detail.  Retail (and by inheritance, Retro) had plenty of questionable code and some places with undefined behaviour, but I do not see any here.

**Comment by tueidj** [comment]
The -= operation is expanded to:
Global_laser_firing_count = Global_laser_firing_count - do_laser_firing_player();

A function call is deemed a synchronization point, therefore Global_laser_firing_count must be evaluated before it is called. So the likely assembly code generated would be loading it into a non-volatile register, calling do_laser_firing_player, then performing the subtraction.
Trust me, I debugged this already to figure out why players with no energy were luring other players into energy centres (their ship discharges a massive amount of lasers as soon as they gain any energy due to Global_laser_firing_count building up). Sprinkle debug output in the code and see what happens to Global_laser_firing_count when you fire lasers with no energy.

**Comment by roncli** [comment]
"Trust me, I debugged this already to figure out why players with no energy were luring other players into energy centres (their ship discharges a massive amount of lasers as soon as they gain any energy due to Global_laser_firing_count building up)."

This does NOT happen in Retro, just tested on 1.4X5.

**Comment by tueidj** [comment]
I didn't say it did, I just said I had debugged it previously and determined this code to be at fault; how does it make sense to perform a subtraction where one of the inputs is a function that sets the other input to zero?

**Comment by tueidj** [comment]
For the record, disassembly from Retro 1.4X5:
`.text:0043493C                 mov     edi, ds:_Global_laser_firing_count
.text:00434942                 test    edi, edi
.text:00434944                 jnz     loc_434AB7
---
.text:00434AB7                 call    _do_laser_firing_player
.text:00434ABC                 sub     edi, eax
.text:00434ABE                 mov     ds:_Global_laser_firing_count, edi`

So do_laser_firing_player() setting Global_laser_firing_count to zero has no effect, as the previous value has already been loaded into edi.

**Comment by roncli** [comment]
Tested this to be false, setting Global_laser_firing_count to zero is working.

game.c:
```
		if (Global_laser_firing_count) {
			HUD_init_message(HM_DEFAULT, "before: %d", Global_laser_firing_count); 
			Global_laser_firing_count -= do_laser_firing_player();
			HUD_init_message(HM_DEFAULT, "after: %d", Global_laser_firing_count); 
		}
```

laser.c:
```
	HUD_init_message(HM_DEFAULT, "rval: %d", rval); 
	return rval;
```

HUD reads:
```
before: 1
rval: 1
after: -1
```

I half wonder if this isn't a compiler thing.  I also wonder why, since this is the only place in the code this function is called, that the global isn't just set within the function.  I mean, it's a *global*. :P

**Comment by roncli** [comment]
Also traced this code, the -= and the setting the global to 0, all the way back to the original D1 release, so this isn't anything any maintainers added over the years.  I'm not inclined to look into this further.

**Comment by tueidj** [comment]
> Tested this to be false, setting Global_laser_firing_count to zero is working.

The disassembled code clearly shows that not to be the case. Were you testing a debug build (compiled without optimizations)?
I would also suggest removing the "before" debug output as it could affect the generated code, and as previously mentioned we are technically in undefined behaviour territory here (see https://en.wikipedia.org/wiki/Sequence_point , "Examples of ambiguity").

**Comment by roncli** [comment]
@vLKp Was fixing this behavior the intent behind dxx-rebirth/dxx-rebirth@788ed1b?

If so, I'm concerned that this is not the correct approach.  It is likely that `Global_laser_firing_count = 0` exists in `do_laser_firing_player` for a reason, and this changes that behavior.

I would just as soon call `do_laser_firing_player` as a `void` instead and call it a day.  That will either leave `Global_laser_firing_count` unchanged or set it to 0, which is basically what is supposed to happen in the code today.

**Comment by vLKp** [comment]
[tueidj wrote](#issuecomment-277624170):

> The -= operation is expanded to:

It is equivalent to that, yes.  Interestingly, expanding it does change the generated code, which could support your assertion that this is undefined behaviour.  After re-reading the sequence point rules, I cannot find anything that I think definitively says whether this is, or is not, undefined behaviour.  When I write it as `var -= f();`, gcc-5.4.0 chooses to reload `var`.  When I write it as `var = var - f();`, gcc-5.4.0 chooses to cache `var`.  This inconsistency certainly looks like an example of undefined behaviour in action.

> `...` due to Global_laser_firing_count building up

This statement bothered me until I got much farther into the thread.  `Global_laser_firing_count` is assigned in various places, but the only statement that modifies it through anything other than `operator=` is the `-=` in question.  I was going to ask, assuming you are correct that the compiler caches an old nonzero value for use as the left hand side of the subtraction, how does `Global_laser_firing_count` build **up**?  However, reading [your later comment with disassembly](#issuecomment-277654044), I see that this is a phrasing issue.  `Global_laser_firing_count` does not build **up** in the bad case.  It remains pinned to its pre-call value because the cached pre-call value is decreased by zero, then written back, overwriting any change made in the called function.

However, even if `Global_laser_firing_count` did somehow attain a large positive value, I would expect that `do_laser_firing_player` would be limited by `Next_laser_fire_time`.

[roncli wrote](#issuecomment-277698058):

> I half wonder if this isn't a compiler thing.

Assuming tueidj is correct that this is undefined behaviour, then it is definitely a "compiler thing." :)  Undefined behaviour is notorious for producing differing results (sometimes wildly so) when the same code is built with different compiler options, versions, etc.  Undefined behaviour should be avoided whenever possible because it can change without warning.

[roncli wrote](#issuecomment-277821406):

> @vLKp Was fixing this behavior the intent behind dxx-rebirth/dxx-rebirth@788ed1b?

No, that change was made solely to discourage the compiler reloading `Global_laser_firing_count` so often because it appeared (perhaps incorrectly) that there was no need to reload it after each function call.

> If so, I'm concerned that this is not the correct approach. It is likely that `Global_laser_firing_count = 0` exists in `do_laser_firing_player` for a reason, and this changes that behavior by ignoring that statement and replacing it with the local `laser_firing_count`.

You are correct that it renders the inner assignment dead.  You may be right that this change is incorrect, as it causes the caching that tueidj asserts is a problem.  I am not convinced that pinning `Global_laser_firing_count` can cause excessive weapons fire.  Since you traced this assignment all the way to the beginning, and the overall structure is confusing, I am less inclined to believe that there is a coherent reason for why it is written this way.  It could be a mistake that never broke the game enough for anyone to report it.

On the bright side, my version is either consistently wrong or consistently right, rather than conditionally correct depending on how the compiler handles undefined behaviour.  That at least makes it easier to reason about the correctness.  I think this bears some additional analysis, if for no other reason than to clean up the confusing semantics.

**Comment by tueidj** [comment]
> After re-reading the sequence point rules, I cannot find anything that I think definitively says whether this is, or is not, undefined behaviour.

It's undefined because the operands for subtraction do not have a defined order of evaluation i.e. the compiler can choose whether to evaluate Global_laser_firing_count either before or after calling do_laser_firing_player(). This definitely matches your observation with gcc-5.4.0.

>  I was going to ask, assuming you are correct that the compiler caches an old nonzero value for use as the left hand side of the subtraction, how does Global_laser_firing_count build up? 

In the original code (and in the codebase I am working from) <a href="https://github.com/CDarrow/DXX-Retro/blob/50ec7ba6e058cc0d90ca332d12059de2700aa69b/d1/main/game.c#L1218">this line</a> is an addition rather than direct assignment:

`Global_laser_firing_count += Weapon_info[Primary_weapon_to_weapon_info[Primary_weapon]].fire_count * (Controls.fire_primary_state || Controls.fire_primary_down_count);`

 I tried to trace when it was changed in rebirth but it was an extremely long time ago; possibly it was originally modified due to this issue...

**Comment by roncli** [comment]
Does anyone know if the D1X SVN still exists?  I've always been curious to see what changes came from that era.

**Comment by vLKp** [comment]
[tueidj wrote](#issuecomment-277945386):

> It's undefined because the operands for subtraction `...`

For regular subtraction, yes, I found various references that make that fairly clear.  I have not found anything that addresses whether `operator-=` is handled specially.  If we were in C++, and dealing with an object that implemented `operator-=`, it would necessarily be well-defined because it would be a method and the right-hand side would need to be collected before the method call could begin.  We are not in C++ (for Retro), nor is it an object, so that rationale need not apply - but I have not found anything that states definitively that it does or does not apply.  The inconsistent results from the compiler certainly support the inference that this is undefined behaviour.  I could see an argument that, for consistency with how overloads must work, that the sequencing would be defined for all uses of `operator-=`.  Evidence from the compiled code suggests that the sequencing is undefined behaviour, at least in the versions of gcc observed so far.  Presumably, this is because it is undefined in the standard, not due to a defect in the compiler.

> `...` in the codebase I am working from `...`

As your link shows, that line is already an assignment in Retro.  In what codebase are you working where this is still `+=`?

> I tried to trace when it was changed in rebirth but it was an extremely long time ago; possibly it was originally modified due to this issue...

History diving is easy. ;)  Iterative `git blame` is the fastest if you do not mind some typing, but `git log -L` can do it too.  The answer is [only shoot when fire button down (fix bug #2271)](/dxx-rebirth/dxx-rebirth/commit/4037fe355f8e5cdef1dd46f5e65cccaa78e69443)  (Jul 29 07:51:47 2005) by @kreatordxx.

> This was also broken in the original code, `...`

That statement is true in far too many places.  However, I am not that interested in whether it was bug-free at retail.  I care whether it works correctly in the latest code of the source ports that retain this function (Rebirth, Retro are known to have it in varying forms).

[roncli wrote](#issuecomment-278017072):

> Does anyone know if the D1X SVN still exists?

I think the D**2**X Subversion still exists (but that's not what you asked for).  Additionally, the d2x history was converted to Git by someone (I think btb).  I subsequently branched it into the Rebirth repository as [`historical/d2x`](/dxx-rebirth/dxx-rebirth/tree/historical/d2x).  With the right setup (described in the README at the tip of that branch), you can get Git to seamlessly trace from Zico's D2X-Rebirth history into the D2X history.  If anyone has a Git import of the D1X history, I'd be happy to add that as another historical branch.

Failing that, the best I can offer is to grab the oldest Git revision of D1X-Rebirth, which will give you a general snapshot of how D1X looked when zico assumed maintainership.  That won't give you history though.

**Comment by tueidj** [comment]
> For regular subtraction, yes, I found various references that make that fairly clear. I have not found anything that addresses whether operator-= is handled specially.

C99 states the following semantics for assignment operators:
`4  The order of evaluation of the operands is unspecified. If an attempt is made to modify the result of an assignment operator (...), the behavior is undefined.`

**Comment by vLKp** [comment]
> C99 states the following semantics for assignment operators:

Yes, and the things I had read to date did not define to my satisfaction whether that sentence was applicable in this context.  However, in reading up on whether `assignment operators` included `operator-=` (it does), I came across a statement that, while not from the standard itself, addresses my question:

[cppreference.com:assignment operators](http://en.cppreference.com/w/c/language/operator_assignment) states in part:

> The expression *lhs @= rhs* is exactly the same as *lhs* __=__ *lhs @* __(__ *rhs* __)__, except that *lhs* is evaluated only once.

That "exactly the same as" phrasing is what I had been hoping to find somewhere.  The compiler clearly behaved as if it were true, but I had not previously found anywhere that explicitly said that.  With that established, your prior remarks about the undefined ordering of the terms of the right-hand side become clearly applicable.  Prior to that phrasing, I had only anecdotal evidence that the compiler treated `-=` as exactly equivalent to its long form.

> But we have no idea what bug #2271 actually was

Which is why it is fortunate that the programmer who wrote that commit message is still active in Rebirth, has an account on Github, and was \@-mentioned in my comment. ;)  He may know what that bug was, or know where to go to read about it.

> input polling runs on its own thread

Introducing threads into Descent is a major step.  I would be very wary of having a secondary thread trying to modify any of the globals used by the main thread.  What exactly are you working on that uses enough Descent code that you need to worry about bugs like this?

**Comment by kreatordxx** [comment]
Here's the bug https://bugzilla.icculus.org/show_bug.cgi?id=2271 ;)

That was so long ago I can't even remember it! But I do remember that D2X bugs were reported using Bugzilla (linked from the D2X website http://icculus.org/d2x/).

**Comment by kreatordxx** [comment]
By the way, would David's comment apply for marking bugs as resolved? I had been waiting for the original poster to mark as resolved in Github.

**Comment by tueidj** [comment]
> Introducing threads into Descent is a major step. I would be very wary of having a secondary thread trying to modify any of the globals used by the main thread. What exactly are you working on that uses enough Descent code that you need to worry about bugs like this?

To be exact it's a thread/interrupt handler combination. This is for the wii homebrew port of Descent which is mostly the original source code, not rebirth or even d1x.
Accessing globals from multiple threads isn't a big deal as long as there's only one writer.

> Here's the bug https://bugzilla.icculus.org/show_bug.cgi?id=2271 ;)

Aha, it's exactly what I thought (and the root cause is this undefined behaviour).

**Comment by roncli** [comment]
For the record, I am going to fix this using the method above (removing the subtraction and just calling the method as a void), but I want to test it first, which I'll probably get to tomorrow. :)

**Comment by vLKp** [comment]
[kreatordxx wrote](#issuecomment-278232874):

> By the way, would David's comment apply for marking bugs as resolved?

It varies by project.  Github does not implement the RESOLVED -> VERIFIED -> CLOSED pattern, so it is a bit more complicated here.  In systems that have that flow, I like a pattern where the committer who published the fix moves the ticket to state RESOLVED, then the original reporter moves it to VERIFIED if the change is satisfactory, and a maintainer moves it to status CLOSED if they are happy with the verification done on the ticket.  That last step can be an important check for the developer to verify that the tester actually tested the fix in full, and ran any required regression suites related to the fix.  For Github, tickets are either open or closed, so I usually leave it open and post a comment asserting that I fixed it.  I then let the original reporter ACK/NAK the success of my change.  If the reporter ACKs the change and does not close the ticket, then I close the ticket on their behalf.

[tueidj wrote](#issuecomment-278233910):

> This is for the wii homebrew port of Descent which is mostly the original source code, not rebirth or even d1x.

May I ask why you decided to roll all the way back to the beginning?  There have been numerous fixes and improvements applied to the source after Parallax released it.  You are forgoing all those changes and likely locking yourself into maintaining your port with substantially less community assistance than if you derived from an actively maintained source port.

> Accessing globals from multiple threads isn't a big deal as long as there's only one writer.

* and your accesses tolerate the inconsistent results that may occur if you read a bigger-than-word sized value
* and your accesses are written in a way that the compiler does not cleverly reorder them due to the generally weak C memory model

If you introduce locking, most of those concerns go away - assuming you trust the reading and writing code to acquire locks when and where they are needed.

[roncli wrote](#issuecomment-278256631):

> For the record, I am going to fix this using the method above (removing the subtraction and just calling the method as a void), but I want to test it first, which I'll probably get to tomorrow. :)

Based on your comments earlier in the thread, I decided to make a similar change for Rebirth.  I went a step further and removed `Global_laser_firing_count` entirely, in preference to recomputing it as needed in `GameProcessFrame`.  Early testing shows no unwanted side effects.

Incidentally, `Auto_fire_fusion_cannon_time` does not seem to work like I would expect from the name.  When I run out of energy while charging a fusion shot, it merely switches weapons and the fusion shot is lost.  This happens in tip and in 0.58.1.

**Comment by tueidj** [comment]
> May I ask why you decided to roll all the way back to the beginning? There have been numerous fixes and improvements applied to the source after Parallax released it. You are forgoing all those changes and likely locking yourself into maintaining your port with substantially less community assistance than if you derived from an actively maintained source port.

Several reasons:
- Far too many dependencies to deal with
- OpenGL is required which the wii/gamecube does not have
- PowerPC architecture means there are portions of code which simply Doesn't Work (assumes little-endian).
- Excessive memory usage compared to the original code (wii only has ~70MB usable RAM, gamecube has 24MB. This includes texture memory.)
- Various other issues associated with assuming target is a PC (dialogs which require keyboard input, libc functions that don't exist in the wii's sdk, etc.)

This isn't a new/upcoming project, it's been publically available / played regularly since 2010 (before the supposed wiiware port was announced) so I don't really need advice on how to maintain it.

**Comment by vLKp** [comment]
> * Far too many dependencies to deal with
> * Excessive memory usage compared to the original code (wii only has ~70MB usable RAM, gamecube has 24MB. This includes texture memory.)

This is a bit vague, but probably a legitimate complaint for a system with such a small memory space.  RSS for my current release build D2X-Rebirth comes in at around 68M.  If your 70MB excludes system libraries, the situation is not as bad, but it could still be pretty cramped.

> * OpenGL is required which the wii/gamecube does not have

Even when built with `opengl=0`?

> * PowerPC architecture means there are portions of code which simply Doesn't Work (assumes little-endian).

Yes, retail mostly assumed little endian.  There has been substantial work to clean up both that and the assumptions about unaligned accesses.

> This isn't a new/upcoming project, it's been publically available / played regularly since 2010 (before the supposed wiiware port was announced) so I don't really need advice on how to maintain it.

Sorry.  I had never heard of it before this thread, and there was nothing on your Github profile page that suggested you had any open projects, so I thought this was something new you were starting.  I wish you luck in backporting all the bug fixes from the other source ports. ;)

**Comment by tueidj** [comment]
>  If your 70MB excludes system libraries, the situation is not as bad, but it could still be pretty cramped.

There basically are no system libraries - wii apps run on bare metal with no OS (extremely similar to MSDOS), so everything must be statically linked.

> Even when built with opengl=0?

When I checked that was broken (<a href=https://github.com/dxx-rebirth/dxx-rebirth/commit/74bcb86cf4c112855556d8e668e653ea20eb0f53>possibly related?<a/>), plus if you're going to use a software renderer what's the point of using an "updated" build? Easier to ditch SDL completely since in that case it only functions as a slow wrapper for framebuffer access.

> Yes, retail mostly assumed little endian.

The retail <i>PC</i> source code did, the <i>mac</i> source code did not (for obvious reasons). It also had quite a few bugfixes that the PC version did not, plus better support for 640x480 (which is the max. resolution of wii/gamecube). But apparently very few people looked at the mac source code.

**Comment by kreatordxx** [comment]
> The retail PC source code did, the mac source code did not (for obvious reasons). It also had quite a few bugfixes that the PC version did not, plus better support for 640x480 (which is the max. resolution of wii/gamecube). But apparently very few people looked at the mac source code.

The retail version of Descent 1 did have separate code bases for PC and Mac. I went over the differences between the code bases with a fine comb and ported the odd feature or two from the Mac code into D1X-Rebirth (e.g. the Dravis funny hat easter egg). The retail Descent 2 code was for PC and Mac combined, and has pretty good handling of endian issues. I largely left the Mac D1 code alone because the endian handling code, bug fixes and higher resolution support was copied from D2X to D1X in dxx-rebirth. That said, I haven't maintained the endian handling code for a while because of Apple switching to Intel processors.

**Comment by vLKp** [comment]
[tueidj wrote](#issuecomment-278924241):

> When I checked that was broken (possibly related?), plus if you're going to use a software renderer what's the point of using an "updated" build?

No, that commit was long after you began your Wii port, and it was to fix some things broken by an earlier commit meant to improve the OGL build.  The SDL-only build shares most of the code with the OGL build, but SCons does not automatically build one when building the other, so bitrot can affect less supported targets.

As for an updated build - you know that most of the improvements are not graphic related, right?  Zico completely redid the networking layer to get rid of IPX, so it now runs natively over UDP, both UDP/IPv4 and UDP/IPv6.  I did extensive improvements to internal consistency checking, including fixing various bugs uncovered by that checking.  My cleanups of some of the GUI code produce notably smaller functions for the same work, which should be a benefit to memory-constrained systems.  There have been various smaller feature patches to Rebirth, both before and after Retro forked off.  The Retro maintainers have added some features of their own, but I do not know whether it would be of interest to you.

More generally, the point of using the updated code is to share the burden of fixing bugs and adding features, rather than requiring every fork to reimplement the same changes.  As hinted at with one of your earlier comments, your code base still has the buildup bug that kreator fixed in 2005, presumably because none of your users ever reported it to you.  What other bugs have been reported to DXX and DXX-Rebirth that we have fixed, that you do not yet have fixed in your copy? ;)  Consider also that sometimes bugs get spotted and fixed in the code before anyone reports them, so reading through a project's bug reports may not give you the full list.

**Comment by tueidj** [comment]
TBH I don't really consider the network changes much of an improvement... it loses compatibility with the "out-of-the-box" dosbox ports from steam/gog and still contains several of the original bugs, one of which I even posted about <a href="http://www.dxx-rebirth.com/frm/index.php/topic,1696.msg22116.html#msg22116">here</a> (dropped power-ups don't have their movement synched correctly between clients).

Also note that I originally commented on that thread because the behaviour of D1 homing missiles was not as intended, you even thanked me for pointing it out.

> My cleanups of some of the GUI code produce notably smaller functions for the same work, which should be a benefit to memory-constrained systems.

What good is that when the dependencies take up far more memory than was reclaimed, and you're stuck with the (unoptimized for ppc, since the assembly code from the mac source port isn't included) software renderer? From experience I can tell you it would struggle to maintain 20fps.

> your code base still has the buildup bug that kreator fixed in 2005

But as we just discovered, it wasn't even fixed correctly - the undefined behaviour that was the underlying cause was still present all along.
Frankly I prefer to take my chances with a fresh start rather than working from code that has been "fixed" by different people over nearly 20 years.

**Comment by roncli** [comment]
> it loses compatibility with the "out-of-the-box" dosbox ports from steam/gog

I don't pretend to speak for the whole community on this, but I'm pretty sure the number of people that care to have IPX compatibility is a pretty low number.

> still contains several of the original bugs, one of which I even posted about <a href="http://www.dxx-rebirth.com/frm/index.php/topic,1696.msg22116.html#msg22116">here</a> (dropped power-ups don't have their movement synched correctly between clients).

Rebirth and Retro are both using GitHub these days, so I imagine that you'll have more success getting things fixed by posting issues the projects as opposed to making a passing comment in a forum thread that was quickly forgotten.

I know I've been trying to make an effort to make sure all of the bugs we're aware of get reported here.  This is the first I've heard of this one, though, so any details you can share regarding the issue are welcome. :)

> Frankly I prefer to take my chances with a fresh start rather than working from code that has been "fixed" by different people over nearly 20 years.

You're certainly not wrong in running your own port.  After all, we're sitting here talking about Rebirth on the Retro fork.  If you're the type that likes digging into the lower level stuff and figuring everything out for yourself rather than use something that deviates from how the original worked, that's awesome, go for it.  Some web developers dislike jQuery for the very same reason... too much bloat, just write the JavaScript yourself.

But let's not dismiss the work that's been done by people that are maintaining a source port to keep a 22-year old game alive.  Sure, we're not going to get everything right, but you've seen the original Descent source code.  They weren't the best devs ever, but they got it done.  We're getting it done, too.  As are you!
