### ISSUE TITLE
Tag releases on GitHub

### ISSUE THREAD

**Issue by ryusei117** [CDarrow/DXX-Retro#79]
When you guys have some time, would you mind tagging the commits corresponding to released versions of DXX Retro? Right now, if you're on GNU/Linux, and you want to obtain the 1.3a and 1.4.X3 source so you can play multiplayer with Windows users, you have to search the commit history to find those releases. Having tags would make things a lot simpler - especially when the commit history becomes huge in the future.

[Here's the DXX-Rebirth GitHub releases page](https://github.com/dxx-rebirth/dxx-rebirth/releases), showing how tags make it easy to get the source of released versions.

Here are the commits of the frequently used Retro versions:

* [DXX Retro 1.3](https://github.com/CDarrow/DXX-Retro/commit/f9a9ead37255d0ad872244a9b383ebccaf49b8a1)
* [D2X Retro 1.3a](https://github.com/CDarrow/DXX-Retro/commit/10a610b8b1cffc199336692a29699c4c92457612) (I ... think this is the one? It's the one with the OS X fixes, so the OS X version couldn't have been built from an earlier commit, and the next commit fixes issue #21, which is still present in 1.3a.)
* [DXX Retro 1.4.X3](https://github.com/CDarrow/DXX-Retro/commit/9075f8f6a99ab93581d04b702a42591a85442228)

**Comment by roncli** [comment]
I'll get these.

@CDarrow Is ryusei correct with the 1.3a release?

**Comment by CDarrow** [comment]
Looks right to me.  The next commit changes the version string to 1.4.X1.

**Comment by roncli** [comment]
Fair enough!

This is in progress.  The tags and releases are in, and I will add the binaries to the Releases page later today.

**Comment by ryusei117** [comment]
Much better - thanks, guys! I know several other GNU/Linux users who also appreciate this.

**Comment by ryusei117** [comment]
So recently, I and a few other players have been trying to determine which commit corresponds to version 1.4.5, but it's proving to be a lot tougher than we thought ... I found commit 0c419e745cfcb322ffab026fed9d3e837277c22f, but its date is only 2016-02-01, and the Windows build of 1.4.5 is labeled 2016-02-11. The latest commit as of 2016-02-11 seems to be 8dee408f23558126f42b2410f38c98bca9123303. When I tried that one, however, it failed to build on Kubuntu 17.04 x86-64. This was the output from `scons`:

* [d1x_retro_8dee408_scons.txt](https://github.com/CDarrow/DXX-Retro/files/1027248/d1x_retro_8dee408_scons.txt)

I then tried the commit before that one, commit 2f7c08e76e2d9ad93c7c607ffa4bc0d524a7d7e7. It built successfully, and I was able to join multiplayer games hosted on version 1.4.5. I'm a bit concerned that I might have the wrong commit, though. Would it be much trouble to tag the correct commit and add it to the releases page?

(Oh yeah, while we're here, one thing I've always wondered - is the version officially named "1.4.5", "1.4.X5", or "1.4X5"? I've seen all of those in various places ... ;-) )

**Comment by roncli** [comment]
Ah yes, that bug, I remember that from when I started working on the Mac version.  I didn't realize I had introduced it.  Apparently FALSE is a Windows thing.  Who knew?  I didn't.  But, I have since fixed it in source.  However, not for a 1.4X5 copy.

If you want similar behavior on 8dee408, either `#define FALSE 0` somewhere temporarily, or just do what I did... change the FALSEs to 0.  But using 2f7c08e is valid and isn't going to lose you much.  The fix in 8dee408 was for an edge case that Ernie found in one of his demos, and only affects demo playback, and is only a shield/energy display bug.  You're totally fine using 2f7c08e instead.

I really should just tag that as 1.4X5 and be done with it.

Side note - I have no idea what the official version numbering is.  It's certainly not semver, so 1.4.5 is wrong.  I use semver in tags just for my sanity.

On the releases page, we're using 1.4X5.  The filename uses 1.4.X5.  The text really doesn't matter, the point is it's the fifth experimental version of version 1.4.

**Comment by roncli** [comment]
Oh, I remember why I didn't tag 1.4X5... it's not in the main branch yet.  Let me just confirm with @CDarrow  that we should catch up the main branch to 2f7c08e and tag it as the 1.4X5 release.

**Comment by roncli** [comment]
Yup, confirmed, we're going to do that.  I'll get 1.4X5 tagged in about an hour and change.

**Comment by ryusei117** [comment]
Awesome, thanks! Yeah, "1.4.X5" vs "1.4X5" isn't a big deal, and I figured the tags were different for some technical reason. I was mostly worried about "1.4.5" ... or the fifth bugfix release after stable version 1.4. :-P

**Comment by roncli** [comment]
Alright, this is as good as it's going to get.  I included:

- Retro 1.3 and 1.3a, as they are the latest stable full releases.  Includes D1 and D2 for both Windows and Mac.
- Retro 1.4X3, as that, despite being beta, is the long-accepted standard on Windows prior to observer mode, and I think is still used by the Rangers at times.  Includes D1 and D2 for Windows.
- Retro 1.4X5, as that's the first observer mode beta version and is still used because some people have problems with 1.4X6.  Includes D1 only for Windows and Mac.
- Retro 1.4X6, as that's the latest beta version.  Includes D1 only for Windows and Mac.

From here on out, we'll only keep the latest stable and important beta versions. :)
